### PR TITLE
"Fixes #13" About Us page of the website

### PR DESCRIPTION
**Pull request by joshimehul**
## Explanation

-This PR fixing the issue "Fixes #13" The About Us WebPage contains nested webpages.This PR also consists of some addition of folders contain pdf's and webpages and images.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ ] The PR is made from a branch that's **not** called "master".
- [x] The PR is made from a branch that is up-to-date with "master".
- [x] The PR's branch is based on "master" and not on any other branch.

### CODE REVIEW

**Review by jkugsiya — CHANGES_REQUESTED** [review]
For small screen sizes this is not a good UX:
image


Also this text is going out of the screen:
image

**Comment by joshimehul** [comment]
okay i will do the changes

**Review by jkugsiya — CHANGES_REQUESTED** [review]
In Introduction li items are leaking out of the screen : 

image

**Review by jkugsiya — CHANGES_REQUESTED** [review]
image


Why blank space below the footer?

**Pull request merged**
