### PR TITLE
added contact us page with responsiveness

### LINKED ISSUE #6: Create Contact us page.
Create a contact us page of the website refer to the original website: www.technonjr.org.

Things to keep in mind:

The page should be responsive that is it should work well on both mobiles and desktop screens.
Good coding practice should be followed.
The Pull request need not be in a single commit.

### PR DESCRIPTION
**Pull request by sahuvivek2000**
## Explanation
Fixes #6: created contact us page with cards containing information and also added map which is not  visible in devices less than 450px as it was causing responsive issue

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR is made from a branch that's **not** called "master".
- [x] The PR is made from a branch that is up-to-date with "master".
- [x] The PR's branch is based on "master" and not on any other branch.

### CODE REVIEW

**Review by jkugsiya — CHANGES_REQUESTED** [review]
image
Contact cards should be in center for the mobile view and no directions(map) is visible for mobile view. Also, as our header or navbar is ready, so include navbar in the page.

**Review by jkugsiya — CHANGES_REQUESTED** [review]
One nit change: Flip the contact (phone) icon.

**Comment by sahuvivek2000** [comment]
All issue solved and a small touch to cards

**Review by jkugsiya — CHANGES_REQUESTED** [review]
image
The cards are still a little bit right-shifted make them in the exact center.

**Comment by sahuvivek2000** [comment]
check whether issue solved or not

**Comment by jkugsiya** [comment]
LGTM @sahuvivek2000 ! Thanks

**Review by jkugsiya — APPROVED** [review]
Merging this PR

**Pull request merged**
